---
title: "Load Raw data"
output: html_document
date: "2025-08-20"
---


Loading R packages and source the "getshots" customized own function
```{r}
source("Get shots.R")
source("Get shots extra.R")
library(jsonlite)
library(tidyverse)
library(ggsoccer)
library(dplyr)
```

Getting players file:
```{r}
players2 <- fromJSON("players.json")
```


Getting processed shots data from JSON files of 5 leagues and join them:
```{r}
shotsEN <- get_shots("events_England.json", "EN")
shotsFR <- get_shots("events_France.json", "FR")
shotsGE <- get_shots("events_Germany.json", "GE")
shotsIT <- get_shots("events_Italy.json", "IT")
shotsSP <- get_shots("events_Spain.json", "SP")
```

Getting shots from JSON file with position included:
```{r}
shotsEN_extra <- get_shots_extra("events_England.json", "EN")
shotsFR_extra <- get_shots_extra("events_France.json", "FR")
shotsGE_extra <- get_shots_extra("events_Germany.json", "GE")
shotsIT_extra <- get_shots_extra("events_Italy.json", "IT")
shotsSP_extra <- get_shots_extra("events_Spain.json", "SP")
```


Collecting datasets
```{r}
shots <- shotsEN %>%
  bind_rows(shotsFR, shotsGE, shotsIT, shotsSP) %>%
  mutate(is_goal2 = ifelse(is_goal == 1, T, F))

write_rds(shots, "all_unblocked_shots.rds")
```


Collection extra datasets:
```{r}
shots_extra <- shotsEN_extra %>%
  bind_rows(shotsFR_extra, shotsGE_extra, shotsIT_extra, shotsSP_extra) %>%
  mutate(is_goal2 = ifelse(is_goal == 1, T, F))

write_rds(shots_extra, "all_unblocked_shots_extra.rds")
```


Plot:
```{r}
ggplot(data = shots, aes(y = y1, x = x1)) +
        annotate_pitch(colour = "white",
                       fill   = "black",
                       limits = FALSE,
                       dimensions = pitch_opta) +
        theme_pitch() +
        theme(plot.background = element_rect(fill = "black"),
              title = element_text(colour = "white")) +
        coord_flip(xlim = c(51, 101),
                   ylim = c(-1, 101)) +
        scale_x_reverse() +
        geom_jitter(aes(fill = factor(is_goal2, levels = c("TRUE", "FALSE"))),
                    alpha = 0.3, shape = 21, size = 0.8) +
        facet_wrap(~is_goal2, nrow = 1) +
        scale_fill_manual(values = c("red", "#00BFFF")) +
        scale_colour_manual(values = c("red", "#00BFFF")) +
        theme(legend.position = c(0.75, 1.12), legend.direction = "horizontal",
              legend.text = element_text(color = "white", size = 8, face = "plain"),
              legend.background = element_rect(fill = "black"),
              legend.key = element_rect(fill = "black"),
              strip.background=element_rect(fill = "black"),
              strip.text = element_text(colour = "black"),
              plot.title = element_text(hjust = 0.07, face = "plain", colour = "white"),
              plot.subtitle = element_text(hjust = 0.07, size = 10, face = "italic", colour = "white"),
              plot.caption = element_text(hjust = 0.95),
              plot.margin = margin(1, 0.2, 0.5, 0.2, "cm")) +
        labs(fill = "Goal?") +
        guides(fill = guide_legend(override.aes = list(alpha = 0.8, size = 2), reverse=T)) +
        labs(title = "Unblocked open play shots",
             subtitle = "Top 5 European Leagues 2017-2018",
             fill = "Goal?")

ggsave("shots_plot.png", width = 10, height = 5)
```






